### ISSUE TITLE
LIST sends directory listing before 150 reply

### ISSUE THREAD

**Issue by hankedan000** [eclipse-ecal/fineftp-server#13]
See the screenshot below where the client sends the "LIST" command, but the server is shown sending the directory listing to full completion prior to sending 150 reply code.
This seems to almost always cause my java FTPClient to fail the first time it make a directory listing call.
Note: I added some debug prints to the sendDirectoryListing() method to print the ec return code as well as the files I have in my FTP directory.
![image](https://user-images.githubusercontent.com/216870/116173391-8044b580-a6da-11eb-83f1-3ee1d3f94788.png)

**Comment by hankedan000** [comment]
It seems like there needs to be some sort of way to make sure the server sends the 150 reply code prior to calling the sendDirectoyrListing() method here.
https://github.com/continental/fineftp-server/blob/master/fineftp-server/src/ftp_session.cpp#L766

**Comment by FlorianReimold** [comment]
Hi Daniel,

I guess this issue never came up, as most FTP Clients start receiving on the data socket only after the Server has sent the 150 reply code. So most clients would force the server to keep those messages in the proper order. I will take a look at it, but it is clear why this can happen in fineftp. I just didn't expect a client to receive the data from the data socket before fineftp even told it that there is some available.
I am wondering though, is your FTP Client a custom client, or do you use a "big" library?

**Comment by hankedan000** [comment]
Hello!
I'm using Apache's FTPClient. I'll try to reduce my client side code down to a simple working example that can reproduce this problem. The interesting thing is that fineFTP and my client code worked just fine when the FTPServer was running on a Raspberry Pi 3, but when I started running my server on a Raspberry Pi Zero (less performant) it started to do this very often.

Here's the Apache FTPClient source code.
https://commons.apache.org/proper/commons-net/javadocs/api-3.6/src-html/org/apache/commons/net/ftp/FTPClient.html

I make a call to FTPClient::listFiles() which simply calls a private method called initiateListParsing()...
![image](https://user-images.githubusercontent.com/216870/116232443-22d75580-a728-11eb-95bc-28739f48008a.png)

initiateListParsing() calls _openDataConnection_() with the LIST command passed in....
![image](https://user-images.githubusercontent.com/216870/116232259-e277d780-a727-11eb-962f-ce34c35e7047.png)

You can see that the _openDataConnection_() method opens and connects to the data socket prior to sending the LIST command on line 927.
![image](https://user-images.githubusercontent.com/216870/116231836-61b8db80-a727-11eb-96fd-89a133c74917.png)

**Comment by hankedan000** [comment]
Here's my example code that use's Apache's FTPClient to reproduce the problem.
``` java
public class SimpleClient {
    private static final Logger logger = Logger.getLogger(SimpleClient.class.getName());
    
    public static void main(String[] args) {
        boolean connected = true;
        String host = "localhost";
        String user = "user";
        String password = "password";
        FTPClient ftpClient = new FTPClient();
        
        try {
            ftpClient.connect(host, 2121);
            
            // After connection attempt, you should check the reply code to
            // verify success.
            int reply = ftpClient.getReplyCode();
            if ( ! FTPReply.isPositiveCompletion(reply)) {
                ftpClient.disconnect();
                logger.log(Level.SEVERE,
                        "FTP server refused connection.");
                connected = false;
            } else {
                // after connecting to the server set the local passive mode
                ftpClient.enterLocalPassiveMode();
            }
            
            // login to server
            if (connected && ! ftpClient.login(user,password)) {
                logger.log(Level.SEVERE,
                        "Failed to login to FTPServer");
                connected = false;
            }
        } catch (IOException ex) {
            logger.log(Level.SEVERE, null, ex);
            connected = false;
        }
        
        if (connected) {
            // List the files on the FTP Server
            for (int i=0; i<10; i++) {
                try {
                    for (FTPFile file : ftpClient.listFiles()) {
                        logger.info(file.getName());
                    }
                    TimeUnit.SECONDS.sleep(1);
                } catch (IOException ex) {
                    logger.log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    logger.log(Level.SEVERE, null, ex);
                }
            }
            
            // disconnect for FTP Server
            try {
                ftpClient.logout();
                ftpClient.disconnect();
            } catch (IOException ex) {
                logger.log(Level.SEVERE, null, ex);
            }
        }
    }
```

Here's an example of the fineFTP server output when running this example (once again with my prints in the sendDirectoryListing() function). You can see the first LIST request worked fine, but the second failed due to the ordering of the reply codes. Every subsequent LIST request fails after that... :(
![image](https://user-images.githubusercontent.com/216870/116235759-3edcf600-a72c-11eb-959c-1fc2f7a14386.png)

**Comment by FlorianReimold** [comment]
I will see what I can do about that. I took a look at the code and I guess the same issue can occur with basically anything the data port is used for (i.e. sending and retrieving files and listing directories).

It would be cool if you could keep that Pi zero around and test whether I really fixed theissue, afterwards.

**Comment by FlorianReimold** [comment]
I had to refactor some code, but I think this should work:
https://github.com/continental/fineftp-server/tree/hotfix/message_order

Can you check out the branch and test on your pi? I haven't compiled it on Linux, yet (just letting you know, if something fails 😉)

**Comment by hankedan000** [comment]
Thanks! This hotfix is certainly much better now, but the race condition still seems to occur if I request LIST enough times.

It used to happen on the 2nd or 3rd request, but now I'm able to get at least 6 or so requests in.
![image](https://user-images.githubusercontent.com/216870/116479882-61ffc680-a84e-11eb-8e6d-3eb974a0a2f0.png)

This is a compilation issue for linux btw. toAbsoluateFtpPath() should be toAbsolutePath()
https://github.com/continental/fineftp-server/blob/hotfix/message_order/fineftp-server/src/ftp_session.cpp#L827

**Comment by hankedan000** [comment]
So I made this just a regular old asio::write() call instead of async_write().
https://github.com/continental/fineftp-server/blob/master/fineftp-server/src/ftp_session.cpp#L80-L99

... it's even better now. It can survive 30+ LIST requests now, but still hits the race condition eventually.

I'm thinking the remaining item is due to the asynchronous nature of io_service.post().
https://github.com/continental/fineftp-server/blob/master/fineftp-server/src/ftp_session.cpp#L59

If we make sendFtpMessage() sync, we really should be returning something to let the caller know things are failing.

**Comment by FlorianReimold** [comment]
Well, that's still not a satisfying result 🙄

I have pushed another commit, that remvoes the `io_service_.post()` call. Can you try again? While I was able to reproduce the issue last time by inserting an artificial sleep, this time I cannot reproduce it.

sendFtpMessage() is async and it is supposed to be. That's what the command_strand is for, so the io_service knows how to synchronize the handlers again while still taking advantage of the internal threadpool. But I somehow remember that `io_service::post(strand.wrap(..))` did not lead to the expected results when sending files over the data socket, so I replaced those calls with a direct post to the responsible strand (which is apparently also deprecated now). And that perfectly synchronized everything, so I assume the same fix will also work for the command_strand.

**Comment by hankedan000** [comment]
Seems like that last commit did the trick!
Your compilation fix for linux wasn't right though. You renamed the `toAbsoluateFtpPath` method to `toAbsolutePath`.

**Comment by FlorianReimold** [comment]
Awesome, thanks for testing! I fixed the typo again (and even tested it on Ubuntu ;) )
