### ISSUE TITLE
Release for Conan

### ISSUE THREAD

**Issue by alejandro-colomar** [eclipse-ecal/fineftp-server#17]
Hi,

I'd like to package this library for [conan center](https://conan.io/center/).  Could you please release a version for that?

Thanks,

Alex

**Comment by FlorianReimold** [comment]
Hi Alejandro,

I would love to, but I have never done anything with Conan in my life and therefore totally lack the experience to do that properly. Can you point me to some kind of tutorial or documentation on what I need to do for that?

Regards
Florian

**Comment by alejandro-colomar** [comment]
Hi Florian,

I meant that I would make the Conan package, and at most I'd ask you a few questions about the library if I have any problems packaging it.

But to do that, I need a version of the library, and a tarball.  Github already provides the tarball when you create a new version, so all you'd need to do is to create a new release in github.

However, if you're interested in the Conan package, I can share with you the branch where I'm doing it (when I create it) so that you can have a look and maybe help me, and also understand what I'm doing.

The conan documentation is here:

https://docs.conan.io/en/latest/reference

And they provide some video tutorials here:

https://academy.jfrog.com/path/conan

BTW, I started using Conan a few weeks ago for a new job.  It's relatively simple, and simplifies the use of "thirdparty" libraries compared to having them in a subdir, and also reduces compilation times, as you don't need to compile the thirdparty every time.  Personally, I still prefer to use system libraries (installed with apt-get), but compared to thirdparty, this is a big improvement.

Cheers,

Alex

**Comment by alejandro-colomar** [comment]
The packaging for the official conan repositories is done in this repository:

https://github.com/conan-io/conan-center-index

You can also read the documentation there if you're interested

A new package is done by creating a subdirectory there.

**Comment by FlorianReimold** [comment]
You can find all Releases here:
https://github.com/continental/fineftp-server/releases

Do these fit your needs? I accidentally disabled the Releases tab a few hours ago when I actually wanted to hide the Packages section. Sorry for that, but that probably was the reason you didn't see the releases. I activated it again.

The tarball is not self-contained, as fineFTP depends on asio. But as I understand Conan, asio would be pulled from another Conan package anyways.
I would be happy to participate in creating a fineFTP Conan Package. It would be great if you could share the branch and feel free to ask any question that arises 😉. If it requires some files or changes in this repository just tell me or create a PR.

We are starting to use Conan internally here at Continental to manage our dependencies, too. I personally however manage the open source fineFTP and [eCAL](https://github.com/continental/ecal) projects, which (of course) cannot depend on any internal Conan packages. So I guess following the process for this simple library is a great start for me to learn about Conan.

**Comment by alejandro-colomar** [comment]
> You can find all Releases here:
> https://github.com/continental/fineftp-server/releases
> 
> Do these fit your needs? I accidentally disabled the Releases tab a few hours ago when I actually wanted to hide the Packages section. Sorry for that, but that probably was the reason you didn't see the releases. I activated it again.

Ahh, yes it was that. Hehe

> 
> The tarball is not self-contained, as fineFTP depends on asio. But as I understand Conan, asio would be pulled from another Conan package anyways.

Yes

> I would be happy to participate in creating a fineFTP Conan Package. It would be great if you could share the branch and feel free to ask any question that arises 😉. If it requires some files or changes in this repository just tell me or create a PR.

Great!  I may start on Monday.  I'll put a link to the branch in this thread.

> 
> We are starting to use Conan internally here at Continental to manage our dependencies, too. I personally however manage the open source fineFTP and [eCAL](https://github.com/continental/ecal) projects, which (of course) cannot depend on any internal Conan packages. So I guess following the process for this simple library is a great start for me to learn about Conan.

Yup :-)

**Comment by alejandro-colomar** [comment]
Sorry for the delay!  I started now.  It's here: https://github.com/alejandro-colomar/conan-center-index/tree/fineftp-server

**Comment by FlorianReimold** [comment]
I assume this issue has been abandoned.
