### ISSUE TITLE
how build .exe support win7

### ISSUE THREAD

**Issue by xtcel** [eclipse-ecal/fineftp-server#18]
I build fineftp in win10 (Visual Studio 2019), When I running .exe in win7, They say:
 "The program can't start because MSVCP140D.dll is missing from your computer."
how build .exe support win7 ?

**Comment by FlorianReimold** [comment]
Hi xtcel,

MSVCP140D.dll is a debug dll from Visual Studio. This dll is not available on any OS, you would have gotten the same message on a clean Windows 10. For shipping you will usually want to ship the Release binaries and have the [Visual Studion Redistributable](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) package installed on the target system. Alternatively you can copy the required Visual Studio DLLs from your development system to the target system. This ways you can also make the debug binary work.

Regards
Florian
