### ISSUE TITLE
when i run it generates a .lib file

### ISSUE THREAD

**Issue by anasouardini-old** [eclipse-ecal/fineftp-server#20]
when i run it generates a .lib file and tries to execute it.

and an error is thrown out.

**Comment by FlorianReimold** [comment]
A lib file is not an executable and cannot be executed by itself. This file is meant to be linked with another executable. It contains all functionality of the FTP Server to be used by your application.
Wikipedia on computing libraries: https://en.wikipedia.org/wiki/Library_(computing)

If you want to get an executable FTP server, please build and execute the example, as described in the "How to checkout and build" section in the Readme of this repository.

**Comment by anasouardini-old** [comment]
so i should build the solution and link the _build to my ftp project?

**Comment by FlorianReimold** [comment]
Yes, you need to integrate the library in your own project.
You can start with the fineftp example project, which already integrates the lib into an .exe. You can modify that project to create whatever you like.

**Comment by anasouardini** [comment]
i already started a project and i want to add this functionality to it. when i copy the example main.cpp to my project's main.cpp i get cannot open "fineftp.server.h". where should i put those headers so it can find them

**Comment by anasouardini** [comment]
when i add it to my project i get :
LINK : fatal error LNK1104: cannot open file 'fineftp.lib'
and inetPton() becomes undefined (used in my project)
