### ISSUE TITLE
CMake configuration fails for iOS 

### ISSUE THREAD

**Issue by agioia-nav** [eclipse-ecal/fineftp-server#23]
$ cmake -B ./iOS_Build -DCMAKE_SYSTEM_NAME=iOS -G Xcode

CMake Error in fineftp-server/CMakeLists.txt:
  Imported target "asio::asio" includes non-existent path

    "Asio_INCLUDE_DIR-NOTFOUND"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

**Comment by FlorianReimold** [comment]
Hi Antonio,

Have you checked out the submodules as written in the [How to checkout and build](https://github.com/continental/fineftp-server#how-to-checkout-and-build) section of the Readme.md?

Regards
Florian

**Comment by agioia-nav** [comment]
Hi Florian, 

thank you for your support. I tried the build of fineftp-server for Mac OS and it works fine (CMAKE_SYSTEM_NAME= Darwin). The 'asio' submodule is cloned correctly.

I'd need to build the fineftp-server for iOS and I noticed that during the CMake configuration phase the find_path command doesn't work fine in Findasio.cmake  
find_path(Asio_INCLUDE_DIR
  NAMES asio.hpp
  PATHS
  ${CMAKE_CURRENT_LIST_DIR}/../thirdparty/asio/asio/include
  include
)

I tried to add the following command after find_path:
set(Asio_INCLUDE_DIR ${CMAKE_CURRENT_LIST_DIR}/../thirdparty/asio/asio/include)

in this way the Asio_INCLUDE_DIR variable is set correctly.

Once I fixed this issue I noticed another issue for iOS build. The configuration of 'example' target fails during 
find_package(fineftp REQUIRED CONFIG)

I'd need only the 'server' target for iOS :)

Regards
A.G.

**Comment by FlorianReimold** [comment]
Hi Antonio,

As I neither own a Mac nor an iPhone or iPad I have no way to debug this. But I am curious if you can make it work. If I understand the asio documentation correctly, they don't officially support iOS.
And can iOS Apps even access the file-system? This obviously is mandatory for any FTP Server.

What you can try to do is compile the fineftp server lib first, install it to some temporary location and then point cmake to that directory by providing `CMAKE_PREFIX_PATH` on command line.

Regards
Florian

**Comment by FlorianReimold** [comment]
Closing, as the original author didn't reply anymore.
