### ISSUE TITLE
Export public library symbols with GenerateExportHeader

### ISSUE THREAD

**Issue by piponazo** [eclipse-ecal/fineftp-server#24]
Hi,

First of all, kudos for this project! I just give it a try to the FTP server and works like a charm. The codebase looks quite clean and the code is easy to read :100: 

While I was trying to integrate your library in my own project, I noticed that you are not exporting the public symbols in the API. Since in my CMake code I have the following lines:

```
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN 1)
```
I get "undefined reference" linking errors when trying to use the `FtpServer` class.

It would be nice to add the export of public symbols by using the GeneraExportHeader feature in CMake:
https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html

I actually would like to contribute to the project with that addition. I hope I can find sometime to do it in the next days :innocent:

**Comment by FlorianReimold** [comment]
Wow, this looks really awesome. To be honest, I didn't even know that CMake is able to manage exported symbols. I will take a deeper look at that on Monday and try to learn about that.

Is your PR finished and conatins all required changes you propose?
