### ISSUE TITLE
In multithreading and high concurrency environment, some smart pointers can`t be released

### ISSUE THREAD

**Issue by linfengca** [eclipse-ecal/fineftp-server#33]
Test 4 clients, each 100 threads, transmission 10000 files(each 2M)，finally, more than ten files were lost, many files can`t be deleted. 
Add trace log for each FtpSession, found that:There are some data connection failures at the client, and the control channel ‘QUIT’ fails.
Then, much FtpSession can`t be released(such as: FtpSession() called 100 times, ~FtpSession() called 90 times, all clients were closed), and data socket in FtpSession  listen always, and files opened in session can`t be deleted.

**Comment by FlorianReimold** [comment]
Hey Linfengca, 

Can you provide some kind of testing script and further information on your operating system?

**Comment by linfengca** [comment]
Thank you for your attention.
Use an FTP client with code for debugging: connet ftp server,login, then the client requests PASV, after the server opens the data socket to listen, the client sends the STOR command, and the server control socket receives the STOR command., then execute: std::shared_ptr<IoFile> file = std::make_shared<IoFile>(local_path, open_mode); then enter: data_ acceptor_. async_accept (*data_socket). At this time, stop client directly (client does not connect the server data socket), and then the file is occupied. std::make_shared<IoFil> cannot be released, FtpSession cannot be released too, they lost themselves...

**Comment by linfengca** [comment]
Thank you for your attention.
Use an FTP client with code for debugging: connet ftp server,login, then the client requests PASV, after the server opens the data socket to listen, the client sends the STOR command, and the server control socket receives the STOR command., then execute: std::shared_ptr<IoFile> file = std::make_shared(local_path, open_mode); then enter: data_ acceptor_. async_accept (*data_socket). At this time, stop client directly (client does not connect the server data socket), and then the file is occupied. std::shared_ptr<IoFile> cannot be released, FtpSession cannot be released too, they lost themselves...
