### ISSUE TITLE
Issue in docker

### ISSUE THREAD

**Issue by imperzer0** [eclipse-ecal/fineftp-server#40]
Good afternoon,
  I've run this server in docker, forwarded port 21 to host network, but I couldn't connect to the server from dolphin. I've tried to run it outside docker, opened up dolphin, and it worked. I've done some research and found out what's wrong. The problem is in Passive mode. Especially in its implementation. Every request of data port, the server would initialize a new random port and send it to the client for communication. Docker has no functionality to forward all ports (if run the server on host network - port 21 can't be open, 'cause of errno 13 (Access denied)). The simplest solution for all of this - set fixed data port.
So, can you please add this feature and let users decide in constructor whether to set fixed data port or leave it as it is?
  Best regards,
  imperzer0.

**Comment by imperzer0** [comment]
Nevermind, I fixed it. Sorry for bothering you.

**Comment by jheaff1** [comment]
May I ask how you fixed this issue? I am facing the same issue
