### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by emre21** [eclipse-ecal/fineftp-server#41]
Do you have any plan for starting from configuration file ?

**Comment by FlorianReimold** [comment]
fineftp-server is a library that is meant for compiling into third-party applications. I don't know what you want to load from the configuration file (probably the user configuration?), but either way this would be the responsibility of the surrounding application. 

There are currently no plans to make this a fully-fledged FTP Server application (beside from the sample application), as too many open source FTP Server Applications already exist.
