### ISSUE TITLE
无法成功登陆

### ISSUE THREAD

**Issue by yangz1998** [eclipse-ecal/fineftp-server#9]
我在浏览器输入了地址和端口号，进入登陆验证阶段后输入用户名密码之后无法成功登陆，系统自动给我退出了服务器

**Comment by FlorianReimold** [comment]
Sorry, but I am speaking English and German only. I am afraid that I cannot help you with your question (?)

**Comment by yangz1998** [comment]
I entered the address and port number in my browser. After entering the login verification phase, I failed to log in to the server successfully after entering the user name and password. The client was prompted to automatically disconnect.
This is the debug message:
```
Successfully added anonymous user.
Successfully added user "123".
Successfully added user "123456".
FTP Server created.
Listening at address 127.0.0.1 on port 2121:
FTP Client connected: 127.0.0.1:36352
FTP >> 220 Welcome to fineFTP Server

FTP << USER anonymous
FTP >> 331 Please enter password

FTP << PASS mozilla@example.com
FTP >> 230 Login successful

FTP << SYST
FTP >> 215 LINUX

Control connection closed by client.
Ftp Session shutting down
FTP Client connected: 127.0.0.1:36354
FTP >> 220 Welcome to fineFTP Server

FTP << USER 123456
FTP >> 331 Please enter password

FTP << PASS 123456
FTP >> 230 Login successful

FTP << SYST
FTP >> 215 LINUX

Control connection closed by client.
Ftp Session shutting down
```

**Comment by FlorianReimold** [comment]
The log indicates that your FTP Client closes the connection after the Server tells it that it is running on Linux. From the FineFTP Server log there is no way to tell why it does that. I have developed and tested fineFTP with CURL and FileZilla as client, but each client behaves differently. What are you using as client?

**Comment by yangz1998** [comment]
I installed Ubuntu 20.04.2 on the virtual box virtual machine, using the Firefox browser that comes with it as the client.

**Comment by FlorianReimold** [comment]
I pushed a commit to the master. FineFTP will from now on alway fake the response of the SYST request end tell the client that it is a "UNIX".
Can you try it again and tell me whether this works for you?

**Comment by yangz1998** [comment]
It works!  thank you very much for your help!
